var filenames = [
  'aumhaa_mod',
  'aumhaa_bindable',
  'aumhaa_midi_io_module',
  'aumhaa_notifier_consts',
  'aumhaa_node_script_proxy',
  'aumhaa_event_emitter',
  'aumhaa_floating_window',
  'aumhaa_button_class',
  'aumhaa_util',
  'aumhaa_LiveAPI_util',
  'aumhaa_chooser',
  'aumhaa_control_class',
  'aumhaa_control_registry',
  'aumhaa_control_surface',
  'aumhaa_dict_module',
  'aumhaa_global_proxy',
  'aumhaa_grid_class',
  'aumhaa_multi_notifier',
  'aumhaa_notification_display',
  'aumhaa_promise',
  'aumhaa_scales',
  'aumhaa_task_server',
  'aumhaa_gui_button_class',
  'aumhaa_gui_control',
  'aumhaa_gui_element',
  'aumhaa_midi_event_router',
  'aumhaa_modes',
  'aumhaa_notifier_class',
  'aumhaa_parameters',
  'aumhaa_preset_component'
]

exports.filenames = filenames;
